"""
Django settings for complaint_portal project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--xhd*r@u#+=naj*5xlam$0an$g1upzn**7hkkz*t++v7nji6q('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
DATE_INPUT_FORMATS = ['%m%d%y']

# Application definition
SITE_ID = 2
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'complaint_portal_app',
    # 'social_django',
    # 'import_export',
    # 'social.apps.django_app.default',
]
API_KEY="d3d15e90-223a-11ee-addf-0200cd936042"
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'scope': [
#             'profile',
#             'email,'
#         ],
#         'AUTH_PARAMS': {'access-type': 'online'}

#     }
# }
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
    #  'social_django.middleware.SocialAuthExceptionMiddleware'

]

ROOT_URLCONF = 'complaint_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        # 'DIRS': [],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'complaint_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    BASE_DIR/ "static"
]
#STATIC_ROOT=os.path.join(BASE_DIR,"staticfiles_build","static")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# addded
# LOGIN_URL = 'login'

# SOCIAL_AUTH_LOGIN_ERROR_URL = '/'
# SOCIAL_AUTH_BACKEND_ERROR_URL = '/authentication_error/'
# SOCIAL_AUTH_URL_NAMESPACE = 'social'

AUTHENTICATION_BACKENDS = (
    # 'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
    # 'social_core.backends.google.GoogleOAuth2',  # for Google authentication
    'django.contrib.auth.backends.ModelBackend',
    # 'social_core.backends.google.GoogleOAuth2',


)

# SOCIAL_AUTH_PIPELINE = (
#     'social_core.pipeline.social_auth.social_details',
#     'social_core.pipeline.social_auth.social_uid',
#     'social_core.pipeline.social_auth.auth_allowed',
#     'social_core.pipeline.social_auth.social_user',
#     'social_core.pipeline.social_auth.associate_by_email',  # associate using email
#     'social_core.pipeline.social_auth.associate_user',
#     'social_core.pipeline.social_auth.load_extra_data',
#     'social_core.pipeline.user.user_details',

# )
### email otp setup  ####
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'shamshad.alam@rentokil-pci.com'
EMAIL_HOST_PASSWORD = 'zgpdotrekmnkmeny'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'shamshad.alam@rentokil-pci.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '940793166952-d916vpoasa1ocmmebh3t41mrbhbgl8er.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

# SOCIAL_AUTH_URL_NAMESPACE = 'social'
#### mobile otp set up ###
TWILIO_ACCOUNT_SID = 'AC7eb3ed107a2161dfec7e08465a7159cc'
TWILIO_AUTH_TOKEN = '1b8d3bf2b877dfbd29272e361e3a3f0b'
TWILIO_PHONE_NUMBER = '(430) 233-7168'

#SOCIAL_AUTH_RAISE_EXCEPTIONS = False
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'redirectuser'


CSRF_TRUSTED_ORIGINS = [
    'https://8000-cs-172903303916-default.cs-asia-southeast1-bool.cloudshell.dev']
