# Generated by Django 4.2 on 2023-06-18 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint_portal_app', '0010_alter_customer_contact_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_type', models.CharField(default='', max_length=50)),
                ('severity', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('remark', models.TextField(max_length=300)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
