# Generated by Django 4.2 on 2023-06-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0013_remove_oe_list_premise_oe_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_complaint',
            name='premise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint_portal_app.premises'),
        ),
    ]
