# Generated by Django 4.2 on 2023-06-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0014_customer_complaint_premise'),
    ]

    operations = [
        migrations.AddField(
            model_name='oe_list',
            name='OE_premise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint_portal_app.premises'),
        ),
    ]
