# Generated by Django 4.2 on 2023-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0016_remove_oe_list_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='oe_list',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
    ]
