# Generated by Django 4.2 on 2023-06-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0017_oe_list_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oe_list',
            name='email',
        ),
    ]
