# Generated by Django 4.2 on 2023-06-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0018_remove_oe_list_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_complaint',
            name='status',
            field=models.CharField(choices=[('under_scrutiny', 'Complaint Under Scrutiny'), ('progressed', 'Progressed'), ('resolved', 'Resolved'), ('not_addressed', 'Not Addressed')], default='under_scrutiny', max_length=50),
        ),
    ]
