# Generated by Django 4.2 on 2023-07-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0020_customer_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_status_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('complaint_request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint_portal_app.customer_complaint')),
            ],
        ),
    ]
