# Generated by Django 4.2 on 2023-07-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0022_customer_status_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_status_log',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer_status_log',
            name='complaint_request_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint_portal_app.customer_complaint'),
        ),
    ]
