# Generated by Django 4.2 on 2023-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_portal_app', '0023_remove_customer_status_log_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_status_log',
            name='complaint_id',
            field=models.IntegerField(default=0),
        ),
    ]
